sudo: required

language: java

services:
  - docker
  
branches:
  only:
    - master

install: true

script:
  - gradle -DTRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER :ccc-service:build :serviceImage:build
  - docker run -d -p 8080:8080 -e CCC_DEBUG=1 --name ccctest sogis/ccc-service
  - gradle :ccc-service:probe
  - docker logs ccctest
  - docker kill ccctest
  - docker rm ccctest

deploy:
  - provider: script
    skip_cleanup: true
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ; docker push sogis/ccc-service:$TRAVIS_BUILD_NUMBER
    on:
      branch: master
